baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'cosmi'
theme = "hugo-theme-itheme-master"




[params]
  defaultCover = 'static/images/Ai-Skin-Blog-Landscape.webp'
  email = 'cosmi.skin@gmail.com'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/floyd-li'
  [[params.socialMedia]]
    name = 'Twitter'
    url = 'https://twitter.com/some-one'
  [[params.blogroll]]
    name = 'cosmi'
    url = 'https://www.cosmi.skin/Dashboard'
